DATA SEGMENT
      NUMBER DW 19H
      ANS DW ?
DATA ENDS

CODE SEGMENT
      ASSUME DS:DATA,CS:CODE
START:
      MOV AX,DATA
      MOV DS,AX
      MOV AX,NUMBER
      MOV CX,0000H
      MOV BX,0FFFFH
REPEAT:
      ADD BX,02H
      INC CX
      SUB AX,BX
      JNZ REPEAT
      MOV ANS,CX
      INT 03H
CODE ENDS
END START